apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: back-end
          image: samynathan/argo_cd_pull_request:client
          ports:
            - containerPort: 8080