apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-demo
  template:
    metadata:
      labels:
        app: server-demo
    spec:
      containers:
        - name: back-end
          image: samynathan/argo_cd_pull_request:client
          ports:
            - containerPort: 80
